

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/micro
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  application:
    name: api-gateway

  #main:
  #  web-application-type: reactive
  cloud:

    application:
      name: api-gateway
      cloud:
        discovery:
          client:
            simple: false
        #loadbalancer:
        #  enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL Eureka-сервера
    register-with-eureka: true # Регистрация сервиса
    fetch-registry: true # Получение реестра других сервисов
  instance:
    prefer-ip-address: true # Использовать IP вместо hostname

  #cloud:
  #  gateway:
  #    routes:
  #      - id: producer-service
  #        uri: lb://PRODUCER-SERVICE
  #        predicates:
  #          - Path=/producer/**
  #      - id: consumer-service
  #        uri: lb://CONSUMER-SERVICE
  #        predicates:
  #          - Path=/consumer/**
  #      - id: auth-service-route
  #        uri: lb://auth-service
  #        predicates:
  #          - Path=/auth/**




server:
  port: 8081