server:
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver