#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: producer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/micro
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      name: crypto-prices
    producer:
      acks: 1
      retries: 0
      compression:
        type: none
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: false
      max-connections: 1

crypto:
  api:
    url: https://api.binance.com/api/v3/ticker/price


server:
  port: 8083